language: php

php:
  - "5.5"

env:
  - DB=mysql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install stable
  - npm install npm -g
  - composer self-update

before_script:
  - composer validate
  - php scripts/configure.php --default
  - composer sync-dev

script: echo done

sudo: false
