language: php

php:
  - "5.5"

env:
  - DB=mysql

mysql:
  adapter: mysql2
  database: claroline_test
  username: travis
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install stable
  - npm install npm -g
  - composer self-update

before_script:
  - composer validate
  - composer run sync

script: phpunit -c app

sudo: false
